#!/bin/bash

set -e

# Prompt
read -p "Run pre-install script? (y/n) " RUN_SCRIPT

if [ $RUN_SCRIPT != "y" ]
then
    echo "Not running pre-install script"
    exit 0
fi

echo "Running pre-install script"

# Check mac/linux
OS_NAME=$(uname)
echo "Detected $OS_NAME operating system..."

# Install zsh using appropriate package manager
if [ $OS_NAME == "Linux" ]
then
    echo "Installing zsh..."
    sudo apt install zsh
elif [ $OS_NAME == "Darwin" ]
then
    echo "Installing zsh..."
    brew install zsh
else
    echo "No control flow for uname output $OS_NAME. Terminating..."
    exit 1
fi

# Install oh-my-zsh
echo 'Installing oh-my-zsh using wget'
OMZDIR="$HOME/.oh-my-zsh"
rm -rf  $OMZDIR
sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
# It will automatically enter the new omz shell here, so when they exit the follow commands will run

read -p "Remove autogenerated OMZ .zshrc? (y/n) " REMOVE_GEN_ZSH

if [ $REMOVE_GEN_ZSH != "y" ]
then
    echo "Not removing..."
    exit 0
fi

# Remove default omz .zshrc
rm -f $HOME/.zshrc