# https://starship.rs/config

format = """
$all\
$fill \
$battery\
$time\
$line_break\
$character
"""

[directory]
style = "bold fg:202"
truncate_to_repo = false
repo_root_style = "bold fg:51"
# Disable truncation
truncation_length = 0
truncation_symbol = ".../"

[git_branch]
style = "bold fg:220"

[time]
disabled = false
format = "[$time]($style)"
style = "bold bright-black"

[[battery.display]]
threshold = 30
style = "bold red"

[fill]
symbol = "~"

[aws]
disabled = true